global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "docmind-backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "docmind-elasticsearch"
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ["elasticsearch:9200"]
