"""Python REPL Tool - sandboxed code execution for calculations."""
import io
import contextlib


class PythonREPL:
    """Sandboxed Python execution for data calculations."""

    ALLOWED_MODULES = {"math", "statistics", "datetime", "json", "re"}

    async def execute(self, code: str) -> dict:
        """
        Execute Python code in a restricted sandbox.
        Only allows safe modules (no os, sys, subprocess, etc.)
        """
        # TODO: [AI_API] The code to execute is generated by LLM (Data Agent)
        # Safety: validate imports before execution
        for line in code.split("\n"):
            if line.strip().startswith("import ") or line.strip().startswith("from "):
                module = line.split()[1].split(".")[0]
                if module not in self.ALLOWED_MODULES:
                    return {"error": f"Module '{module}' is not allowed", "output": ""}

        stdout = io.StringIO()
        try:
            with contextlib.redirect_stdout(stdout):
                exec(code, {"__builtins__": {}})
            return {"output": stdout.getvalue(), "error": None}
        except (SyntaxError, NameError, TypeError, ValueError, ArithmeticError) as e:
            return {"output": "", "error": str(e)}
